### ISSUE TITLE
target option

### ISSUE THREAD

**Issue by jorauch** [jacoborus/directus-extension-display-link#2]
Hi and thanks for the very useful extension. 
Is it possible to config the target of the link? 
Actually it is always "_blank" right? 

I have some ssh:// link and with target _blank it always open an empty browser window.

**Comment by jacoborus** [comment]
Yes, the `target="_blank"` is hard coded atm, but I'll make it optional.

**Comment by jacoborus** [comment]
Fixed in 0fbb04be3a8370509f2a8908eb076b462dec7d46
