### ISSUE TITLE
Can't find the field

### ISSUE THREAD

**Issue by narduin** [jacoborus/directus-extension-display-link#4]
Hello,

I'm very sorry to ask this but I can't seem to find the `link` option when creating a new field…
I looked inside almost every type of fields (string, text, alias, etc.) without seeing it.

I'm using directus v9.21.0

Thank you!

**Comment by jacoborus** [comment]
Hi @narduin , if you selected "string" as type, it should be under the "Display" options when you create a field in advance mode.

**Comment by narduin** [comment]
Thanks!

**Comment by Kaplas85** [comment]
@jacoborus Could this be a bug? I'm trying to convert this field into a link to open WhatsApp using wa.me, but I can't find a way to create the link anywhere.


![Image](https://github.com/user-attachments/assets/d152c37b-a699-497b-8796-2ba87f64111f)

![Image](https://github.com/user-attachments/assets/f534069d-f23c-45b1-95e5-472bfe423fcc)
